apiVersion: v1
kind: Pod
metadata:
  name: rna-seq
spec:
  restartPolicy: Never
  containers:
  - name: rna-seq
    image: kiwenlau/tophat-cufflinks
    command: ["/usr/local/bin/bowtie2-build", "/tmp/rnaseq/data/ggal_1_48850000_49020000.Ggal71.500bpflank.fa", "/tmp/rnasoutput/index/genome_index"]
    volumeMounts:
    - name: redis-persistent-storage
      mountPath: /tmp/rnaseq
  volumes:
    - hostPath:
      name: redis-persistent-storage
      path: /root/mac/rnaseq-kubernetes/rnaseq
